### ISSUE TITLE
Can we fix this warning.

### ISSUE THREAD

**Issue by sanandnarayan** [Codebrahma/serverless-gatsby#32]
<img width="1802" alt="screen shot 2018-08-15 at 11 55 26" src="https://user-images.githubusercontent.com/433334/44167175-4fcfa100-a082-11e8-9401-25aa5dfcd5ab.png">

On the homepage in dev mode , i get this warning. I am not sure why it is being passed to the dom, even though you have caught the prop in `src/components/NavLink/index.js:8` 

Can you let me know what i am missing?

**Comment by Kameshwaran** [comment]
solved.
